FROM docker.io/golang:1.25-trixie AS builder

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y \
    build-essential \
    git

WORKDIR /build
RUN git clone https://github.com/bemasher/rtlamr
WORKDIR /build/rtlamr
RUN go build

FROM docker.io/python:3.14

COPY --from=builder /build/rtlamr/rtlamr /usr/local/bin/
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync
COPY ./ ./
CMD ["uv", "run", "--no-sync", "main.py"]
